version: '3.2'
services:
  postgres:
    build:
      context: .
      dockerfile: DockerfileDb
    container_name: postgresdb
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ~/.docker-conf/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - default_network
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - default_network
  aqbackend:
    build:
      context: .
      dockerfile: DockerfileApp
    container_name: aqbackend
    hostname: aqbackend
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - default_network    
networks:
  default_network:
    driver: bridge
